### ISSUE TITLE
find the mistake

### ISSUE THREAD

**Issue by EddieTheEd** [NotTacoz/startpage#3]
<img width="957" alt="image" src="https://user-images.githubusercontent.com/103193479/167542240-f4c91023-1607-483c-8ccf-302245ac099c.png">

**Comment by tms-h** [comment]
192.168.1.0

**Comment by tms-h** [comment]
Background fix: possibly an error with the image file you have chosen, if this is the case, simply upload your image here so I can inspect it.
Overlayed boxes: Change text font size in settings and voila.
No weather: weatherapi possibly down, you can check settings and post a console report.

<3

**Comment by tms-h** [comment]
also, since you used to use firefox: https://addons.mozilla.org/en-US/firefox/addon/start-page-tab/

**Comment by EddieTheEd** [comment]
Wait you need to use firefox? I was using chrome lol

**Comment by EddieTheEd** [comment]
my bad, the problem is that it says 12:22 AM but its 12:22 PM

**Comment by EddieTheEd** [comment]
<img width="192" alt="image" src="https://user-images.githubusercontent.com/103193479/167619834-808985d6-65a0-4027-b4f6-e5098a5bf6bc.png">

tan(x) when x = 90 degrees be like

**Comment by tms-h** [comment]
wait why does it do that what version of startpage are you using

**Comment by EddieTheEd** [comment]
the most recent release

**Comment by EddieTheEd** [comment]
btw i use on chrome, i opened the release thing on github and followed instructions

**Comment by tms-h** [comment]
i uploaded the latest version see if that fixes the problem

**Comment by EddieTheEd** [comment]
thank you for certified boy lover

**Comment by EddieTheEd** [comment]
the problem is fixed :)
